<?php require VIEWS_PATH . 'includes/header.phtml';?>

<main role="main">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron text-center">
        <div class="container">
            <h1 class="display-3"> Olá! </h1>
            <p> Página Contato </p>
        </div>
    </div>

    <div class="container">
        <!-- Example row of columns -->
        <div class="row">
            <div class="col-md-12 text-center">
                <h2> Titulo </h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
            </div>
        </div>

        <div class="row">

            <div class="col-md-8">
                <h2>Heading</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <h2>Formulário</h2>
                <form action="" class="form">
                    <div class="form-group">
                        Nome: <input type="text" class="form-control" placeholder="NOME">
                    </div>
                    <div class="form-group">
                        Nome: <input type="text" class="form-control" placeholder="NOME">
                    </div>
                    <button class="btn btn-success">ENVIAR</button>
                </form>
            </div>

        </div>

        <hr>

    </div> <!-- /container -->

</main>

<?php require VIEWS_PATH . 'includes/footer.phtml';?>
